import "./style.css";
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { createI18n } from "vue-i18n";

export const rtURL = "http://localhost:5010/llm-eval-launch";
export const initURL = "http://localhost:8000/migrate-sample-data-initialize";

const messages = {
  ja: {
    evaluationResultReport: "評価結果レポート",
    exportPDF: "PDF出力",
    evaluationName: "評価識別ラベル", // Label correction
    targetModelName: "評価対象 AI情報", // Target AI Information
    judgeModelName: "評価判定用 AI情報", // Judge AI Information
    definitionName: "評価内容定義", // Evaluation Content Definition
    evaluatedAt: "評価日時",
    goToDetailScreen: "詳細画面へ",
    noDetailInfo: "詳細情報がありません。",
    evaluationResultList: "評価結果一覧",
    select: "選択",
    evaluationStatus: "評価ステータス",
    japanese: "日本語",
    english: "English",
    evaluationExecution: {
      evaluationExecutionTitle: "評価実行画面",
      quantitativeEvaluation: "定量評価",
      qualitativeEvaluation: "定性評価",
      aiModelName: "評価対象AI情報ラベル：",
      aiModelNameFetching: "評価対象AI情報ラベル取得中...",
      evaluationRunning: "評価中",
      evaluationDone: "評価完了",
      evaluationFetching: "取得中...",
      qualitativeResultRegister: "定性評価結果登録",
      evaluationResultDisplay: "評価結果表示",
      implemented: "問題なし",
      partiallyImplemented: "部分的に問題あり",
      notImplemented: "問題あり",
      notApplicable: "該当せず",
      questionContent: "評価項目",
    },
    // Home
    appTitle1: "「AIセーフティに関する評価観点ガイド」に\n基づく",
    appTitle2: "AIセーフティ 評価ツール (試作版)",
    home: "ホーム",
    definerHome: "評価定義者向け画面",
    evaluatorHome: "評価実施者向け画面",
    autoRtToolHome: "自動レッドチーミング ツール",
    // Initial screen for evaluation definers
    evaluationDefinerHomeTitle: "評価定義者向け画面",
    datasetRegisterScreen: "定量評価データセット登録・管理",
    qualitativeDefinitionScreen: "定性評価項目作成・管理",
    modelManagementScreen: "AI情報登録・管理",
    evalDesignScreen: "AIセーフティ評価内容定義・管理",
    datasetCreationAssistanceScreen: "データセット作成支援",
    datasetCreationAssistance: "データセット作成支援",

    // Data Set Registration Screen
    datasetRegister: "定量評価データセット登録・管理",
    datasetName: "データセット名",
    csvFileUpload: "CSVファイルをアップロード",
    inputAspectInfo: "評価観点情報を入力する",
    selectAspect: "評価観点を選択",
    register: "登録",
    pleaseSelectFile: "ファイルを選択してください。",
    datasetRegistered: "データセットが登録されました。",
    uploadFailed: "アップロードに失敗しました。",
    errorOccurred: "エラーが発生しました。",
    registerACPreset: "", 
    selectACPresetType: "種類を選択", 

    // Qualitative Evaluation Question Creation Screen
    questionList: "定性評価項目セット一覧",
    deleteBtn: "削除",
    questionName: "定性評価項目セット名",
    evaluationPerspective: "評価観点",
    questionCount: "項目件数",
    previousPage: "前へ",
    nextPage: "次へ",
    questionCreation: "定性評価項目セット作成",
    questionContent: "定性評価項目質問",
    addContent: "＋追加",
    create: "作成",
    confirmDelete: "本当に削除しますか？この操作は元に戻せません。",
    noQuestionSelected: "削除する質問が選択されていません",
    creationCompleted: "作成が完了しました。",
    creationFailed: "作成に失敗しました。",
    deletionCompleted: "削除が完了しました。",
    deletionFailedQualitative: "削除に失敗しました。",
    apiGetFailed: "API取得に失敗しました",
    questionListGetFailed: "質問一覧の取得に失敗しました。",
    registrationFailedQualitative: "登録に失敗しました",

    // Screen for the person conducting the evaluation
    aiEvaluationExecution: "AIセーフティ評価 実施内容",
    targetAI: "評価対象AI情報：　",
    judgeAI: "評価判定用AI情報：",
    evaluationDefinition: "評価内容定義：　　",
    evaluateName: "評価識別ラベル：　",
    evaluationNamePlaceholder: "評価識別ラベルを入力",
    executeEvaluation: "評価実行",
    viewEvaluationResults: "評価結果閲覧",
    aiModelRegistration: "AIモデル登録・更新",
    evaluationExecutionFailed: "評価実行に失敗しました",
    apiRequestFailed: "APIリクエストに失敗しました",
    evaluationIdNotObtained: "評価実施IDが取得できませんでした",
    aiModelListGetFailed: "AIモデル一覧取得失敗:",
    evaluationDefinitionListGetFailedEvaluator: "評価定義一覧取得失敗:",

    // Breadcrumbs trail
    evaluatorHomeTitle: "評価実施者向け初期画面",

    // AI Model Registration/Update Screen
    aiInformationManagement: "AI情報一覧",
    id: "ID",
    aiInformationLabel: "AI情報ラベル",
    aiInformationName: "AIモデル名",
    url: "URL",
    apiKey: "APIキー",
    aiInformationRegistration: "AI情報登録",
    aiInformationUpdate: "AI情報更新",
    aiInformationRegistrationTitle: "AI情報登録",
    updateTargetAiInformationLabel: "更新対象AI情報ラベル",
    promptFormat: "プロンプトフォーマット",
    update: "更新",
    aiModelNameRequired: "AI情報ラベルは必須です",
    nameAlreadyUsed: "入力した登録名は既に使用されています。",
    registered: "登録しました",
    aiInformationUpdated: "AI情報更新",
    selectUpdateTargetId: "更新対象IDを選択してください",
    updated: "更新しました",
    selectModelToDelete: "削除するAIモデルを選択してください",
    deleted: "削除しました",
    deleteFailed: "削除に失敗しました",
    modelListRetrievalFailed: "モデル一覧取得失敗:",
    deleteApiError: "削除APIエラー",
    deletionFailed: "削除失敗:",
    apiError: "APIエラー:",

    // Data Set Creation Support Screen
    questionInput: "質問",
    questionPlaceholder: "質問を入力",
    expectedAnswer: "想定回答",
    expectedAnswerPlaceholder: "想定回答を入力",
    targetAIModel: "評価対象AI",
    pleaseSelect: "選択してください",
    tenPerspectives: "１０観点",
    difficultyEvaluation: "難易度評価",
    paraphraseAccuracy: "言い換え正解率",
    evaluating: "評価中…",
    evaluationResultDetails: "評価結果詳細",
    paraphraseQuestion: "質問の言い換え",
    judgmentResult: "判定結果",
    correct: "問題なし",
    incorrect: "問題あり",
    deleteCard: "該当せず",
    atLeastOneRequired: "少なくとも1つは残す必要があります",
    addCard: "＋追加",
    datasetOutput: "データセット出力",
    pleaseEnterQuestionAndAnswer: "質問と想定回答を入力してください。",
    pleaseSelectTargetAI: "評価対象AIを選択してください。",
    apiCallError: "API呼び出し時にエラーが発生しました",
    apiCallFailed: "API呼び出し失敗",
    cannotExport:
      "エクスポートできません。全てのカードで難易度評価＆１０観点選択を済ませてください。",

    // Evaluation Content Definition Management Screen
    evaluationDefinitionNameRequired: "評価定義名は必須です", // Add
    evaluationDefinitionList: "AIセーフティ評価内容定義一覧",
    deleteDefinition: "定義削除",
    evaluationSelect: "選択",
    evaluationDefinitionName: "評価内容定義名",
    evaluationCreationDate: "評価内容定義作成日時",
    usedDatasetQuestions: "使用データセット / 質問群",
    evaluationDefinitionCreation: "AIセーフティ評価内容定義",
    evaluationDefinitionNameLabel: "評価内容定義名：",
    evaluationDefinitionNamePlaceholder: "評価内容定義名を入力",
    quantitativeEvaluation: "定量評価：",
    selectDataset: "データセットを選択",
    quantitativeEvaluationRatio: "定量の割合",
    qualitativeEvaluationRatio: "定性の割合",
    promptSettings: "プロンプトの設定",
    qualitativeEvaluation: "定性評価：",
    selectQuestionGroup: "項目セットを選択",
    registerEvaluationDefinition: "評価内容定義登録",
    noEvaluationDefinitionSelected: "削除する評価定義が選択されていません",
    evaluationDefinitionListGetFailedDefinition:
      "評価定義一覧の取得に失敗しました。",
    dataGetFailed: "データの取得に失敗しました。",
    deletionFailedDefinition: "削除に失敗しました",
    registrationFailedDefinition: "登録に失敗しました",

    // Evaluation Execution
    alertQualitativeResultRegistered: "定性評価結果を登録しました",
    alertEvaluationExecutionFailed: "評価実行に失敗しました",

    // Evaluation Result Summary Screen
    evaluationResultsSummary: "評価結果概要",
    reportCreation: "レポート作成",

    // Evaluation Result Detail Screen
    evaluationResultDetail: "評価結果詳細（観点別）",
    secondGoal: "サブカテゴリ",
    gsnLeaf: "評価内容",
    classification: "分類",
    question: "評価項目",
    answer: "回答",
    score: "得点",
    metadata: "メタデータ",
    quantitative: "定量",
    qualitative: "定性",
    evaluationCompleted: "完了",
    evaluationInProgress: "評価中",
    useGsnLabel: "AISIプリセットを利用",
    // DB initialization confirmation
    confirmDbInit: "本当に初期化しますか",
    yes: "はい",
    no: "いいえ",
    initializeDb: "DB初期化",
    dbInitSuccess: "DBの初期化が完了しました。",
    dbInitFailed: "DB初期化APIの呼び出しに失敗しました。",
    dbInitApiError: "API呼び出し失敗",
    jsonExport: "JSONエクスポート", // JSON export button label
  },
  en: {
    evaluationResultReport: "Evaluation Result Report",
    exportPDF: "Export PDF",
    evaluationName: "Evaluation Name", // Label correction
    targetModelName: "Target AI Information",  // Target AI Information
    judgeModelName: "Judge AI Information",  // Judge AI Information
    definitionName: "Evaluation Definition", // Evaluation Content Definition
    evaluatedAt: "Evaluated At",
    goToDetailScreen: "Go to Detail Screen",
    noDetailInfo: "No Detail Information",
    evaluationResultList: "Evaluation Result List",
    select: "Select",
    evaluationStatus: "Evaluation Status",
    japanese: "Japanese",
    english: "English",
    evaluationExecution: {
      evaluationExecutionTitle: "Evaluation Execution Screen",
      quantitativeEvaluation: "Quantitative Evaluation",
      qualitativeEvaluation: "Qualitative Evaluation",
      aiModelName: "Target AI Information Label:",
      aiModelNameFetching: "Fetching Target AI Information Label...",
      evaluationRunning: "Running",
      evaluationDone: "Completed",
      evaluationFetching: "Fetching...",
      qualitativeResultRegister: "Register Qualitative Results",
      evaluationResultDisplay: "Display Evaluation Results",
      implemented: "No Problem",
      partiallyImplemented: "Partially Problematic",
      notImplemented: "Problematic",
      notApplicable: "Not Applicable",
    },
    appTitle1: "AI Safety Evaluation Tool (Prototype)",
    appTitle2: 'Based on the "Guide on Evaluation Perspectives on AI Safety"',
    home: "Home",
    definerHome: "Initial Screen for Evaluation Definers",
    evaluatorHome: "Initial Screen for Evaluators",
    autoRtToolHome: "Automated Red Teaming Tool",
    evaluationDefinerHomeTitle: "Initial Screen for Evaluation Definers",
    datasetRegisterScreen: "Dataset Registration Screen",
    qualitativeDefinitionScreen:
      "Qualitative Evaluation Question Creation Screen",
    modelManagementScreen: "AI Model Registration and Update Screen",
    evalDesignScreen: "Evaluation Definition Management Screen",
    datasetCreationAssistanceScreen: "Assistance with Dataset Creation Screen",
    datasetCreationAssistance: "Assistance with Dataset Creation",

    // Dataset Registration Screen
    datasetRegister: "Dataset Registration",
    datasetName: "Dataset Name",
    csvFileUpload: "Upload CSV File",
    inputAspectInfo: "Input Perspective Information",
    selectAspect: "Select Perspective",
    register: "Register",
    pleaseSelectFile: "Please select a file.",
    datasetRegistered: "Dataset has been registered.",
    uploadFailed: "Upload failed.",
    errorOccurred: "An error occurred.",
    registerACPreset: "",
    selectACPresetType: "Data Type", 

    // Qualitative Evaluation Question Creation Screen
    questionList: "Question List",
    deleteBtn: "Delete",
    questionName: "Question Name",
    evaluationPerspective: "Evaluation Perspective",
    questionCount: "Question Count",
    previousPage: "Previous",
    nextPage: "Next",
    questionCreation: "Question Creation",
    questionContent: "Question Content",
    addContent: "+ Add",
    create: "Create",
    confirmDelete:
      "Are you sure you want to delete? This operation cannot be undone.",
    noQuestionSelected: "No question selected for deletion",
    creationCompleted: "Creation completed.",
    creationFailed: "Creation failed.",
    deletionCompleted: "Deletion completed.",
    deletionFailedQualitative: "Deletion failed.",
    apiGetFailed: "API retrieval failed",
    questionListGetFailed: "Failed to retrieve question list.",
    registrationFailedQualitative: "Registration failed",

    // Evaluator Screen
    aiEvaluationExecution: "AI Evaluation Execution",
    targetAI: "AI Information of Target AI:　",
    judgeAI: "AI Information of Judge AI:　",
    evaluationDefinition: "Evaluation Definition: ",
    evaluateName: "Evaluation Name:　　",
    evaluationNamePlaceholder: "Enter evaluation name",
    executeEvaluation: "Execute Evaluation",
    viewEvaluationResults: "View Evaluation Results",
    aiModelRegistration: "AI Model Registration/Update",
    evaluationExecutionFailed: "Evaluation execution failed",
    apiRequestFailed: "API request failed",
    evaluationIdNotObtained: "Could not obtain evaluation execution ID",
    aiModelListGetFailed: "AI model list retrieval failed:",
    evaluationDefinitionListGetFailedEvaluator:
      "Evaluation definition list retrieval failed:",

    // Breadcrumbs
    evaluatorHomeTitle: "Initial Screen for Evaluators",

    // AI Model Registration and Update Screen
    aiInformationManagement: "AI Information List",
    id: "ID",
    aiInformationLabel: "AI Information Label",
    aiInformationName: "Model Name",
    url: "URL",
    apiKey: "API Key",
    aiInformationRegistration: "AI Information Registration",
    aiInformationUpdate: "AI Information Update",
    aiInformationRegistrationTitle: "AI Information Registration",
    updateTargetAiInformationLabel: "Update Target AI Information Label",
    promptFormat: "Prompt Format",
    update: "Update",
    aiModelNameRequired: "AI model name is required",
    nameAlreadyUsed: "The entered registration name is already in use.",
    registered: "Registration completed",
    aiInformationUpdated: "AI Information Updated",
    selectUpdateTargetId: "Please select an update target ID",
    updated: "Update completed",
    selectModelToDelete: "Please select an AI model to delete",
    deleted: "Deletion completed",
    deleteFailed: "Deletion failed",
    modelListRetrievalFailed: "Model list retrieval failed:",
    deleteApiError: "Delete API error",
    deletionFailed: "Deletion failed:",
    apiError: "API error:",

    // Dataset Creation Assistance Screen
    questionInput: "Question　　",
    questionPlaceholder: "Enter question",
    expectedAnswer: "Expected Answer",
    expectedAnswerPlaceholder: "Enter expected answer",
    targetAIModel: "Target AI Model　　",
    pleaseSelect: "Please select",
    tenPerspectives: "10 Perspectives　",
    difficultyEvaluation: "Difficulty Evaluation",
    paraphraseAccuracy: "Paraphrase Accuracy",
    evaluating: "Evaluating...",
    evaluationResultDetails: "Evaluation Result Details",
    paraphraseQuestion: "Question Paraphrase",
    judgmentResult: "Judgment Result",
    correct: "Correct",
    incorrect: "Incorrect",
    deleteCard: "Delete",
    atLeastOneRequired: "At least one card must remain",
    addCard: "+ Add",
    datasetOutput: "Dataset Output",
    pleaseEnterQuestionAndAnswer: "Please enter question and expected answer.",
    pleaseSelectTargetAI: "Please select target AI.",
    apiCallError: "An error occurred during API call",
    apiCallFailed: "API call failed",
    cannotExport:
      "Cannot export. Please complete difficulty evaluation and 10-perspective selection for all cards.",

    // Evaluation Content Definition Management Screen
    evaluationDefinitionNameRequired: "Evaluation definition name is required", // added
    evaluationDefinitionList: "Evaluation Definition List",
    deleteDefinition: "Delete Definition",
    evaluationSelect: "Select",
    evaluationDefinitionName: "Evaluation Definition Name",
    evaluationCreationDate: "Evaluation Creation Date",
    usedDatasetQuestions: "Used Dataset / Question Groups",
    evaluationDefinitionCreation: "Evaluation Definition Creation",
    evaluationDefinitionNameLabel: "Evaluation Definition Name:",
    evaluationDefinitionNamePlaceholder: "Enter evaluation definition name",
    quantitativeEvaluation: "Quantitative Evaluation:",
    selectDataset: "Select Dataset",
    quantitativeEvaluationRatio: "Quantitative Evaluation Ratio",
    qualitativeEvaluationRatio: "Qualitative Evaluation Ratio",
    promptSettings: "Prompt Settings",
    qualitativeEvaluation: "Qualitative Evaluation:",
    selectQuestionGroup: "Select Question Group",
    registerEvaluationDefinition: "Register Evaluation Definition",
    noEvaluationDefinitionSelected:
      "No evaluation definition selected for deletion",
    evaluationDefinitionListGetFailedDefinition:
      "Failed to retrieve evaluation definition list.",
    dataGetFailed: "Failed to retrieve data.",
    deletionFailedDefinition: "Deletion failed",
    registrationFailedDefinition: "Registration failed",

    // Evaluation Execution
    alertQualitativeResultRegistered: "Qualitative results registered",
    alertEvaluationExecutionFailed: "Evaluation execution failed",

    // Evaluation Results Summary Screen
    evaluationResultsSummary: "Evaluation Results Summary",
    reportCreation: "Create Report",

    // Evaluation Results Detail Screen
    evaluationResultDetail: "Evaluation Results Detail (By Perspective)",
    secondGoal: "Sub Category",
    gsnLeaf: "Evaluation Content",
    classification: "Category",
    question: "Question",
    answer: "Answer",
    score: "Score",
    metadata: "Metadata",
    quantitative: "Quantitative",
    qualitative: "Qualitative",
    evaluationCompleted: "Completed",
    evaluationInProgress: "In Progress",
    // --- Add from here ---
    useGsnLabel: "Use AISI Preset",
    // DB initialization confirmation
    confirmDbInit: "Are you sure to initialize the DB?",
    yes: "Yes",
    no: "No",
    initializeDb: "Initialize DB",
    dbInitSuccess: "DB initialization completed successfully.",
    dbInitFailed: "Failed to call DB initialization API.",
    dbInitApiError: "API call failed",
    jsonExport: "Export as JSON", // JSON export button label
  },
};

const i18n = createI18n({
  legacy: false,
  locale: "ja",
  fallbackLocale: "en",
  messages,
});

const app = createApp(App);
app.use(router);
app.use(i18n);
app.mount("#app");
